### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jeffryjdelarosa** [herohat/ncf_dgii_reports#1]
Al Intentar Instalar 

Este es el Error que sale:

>   File "/odoo/odoo-server/odoo/models.py", line 447, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
TypeError: Model 'dgii.report' inherits from non-existing model 'ir.needaction_mixin'

> TypeError: Model 'dgii.report' inherits from non-existing model 'ir.needaction_mixin'.
2019-01-03 02:10:06,022 22377 ERROR demo odoo.http: Exception during JSON request handling.

> TypeError: Model 'dgii.report' inherits from non-existing model 'ir.needaction_mixin'.
2019-01-03 02:10:06,132 22377 INFO demo odoo.modules.loading: loading 1 modules...

**Comment by jeffryjdelarosa** [comment]
Resuelto, el problema por el nombre de la Carpeta

**Comment by manuelpgs** [comment]
Good!
